version: "3"
services:
       app:
           container_name: weatherapi_c
           restart: always
           build: ./api
           ports:
             - 4000:4000
           volumes:
             - ./api:/app
             - ./api:/node_modules
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             ports:
               - 27017:27017
       newswhetherapp:
            build : ./newswhetherapp
            container_name : newswhether_c
            ports:
             - 3000:3000
            stdin_open: true
            tty : true
